# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: security_development
  pool: 5
  username: confabuser
  password: confabdevel
  host: localhost
  port: 5432
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: security_development
  pool: 5
  username: confabuser
  password: confabdevel
  host: localhost
  port: 5432
  timeout: 5000
